services:
  assistant:
    ports:
      - 8000:8000

  intent_catcher:
    ports:
      - 8001:8000

  llm_vicuna13b:
    ports:
      - 8002:8000

  planner:
    ports:
      - 8003:8000

  llm_llama3:
    ports:
      - 8004:8000

  machine_translation:
    ports:
      - 8005:8000

  gigachat:
    ports:
      - 8006:8000
  
  seg_and_track:
    ports:
      - 8007:8000
